spring:
  application:
    name: idpportal

  profiles:
    active: dev

  mybatis:
    mapper-locations: classpath:/mappers/*.xml
    type-aliases-package: com.kstec.idp.portal.domain
    configuration:
      map-underscore-to-camel-case: true
      default-statement-timeout: 30 # 모든 쿼리 기본 타임아웃 30초