spring:
  datasource:
    url: #데이터베이스 접속 URL
    username: #데이터베이스 username
    password: #데이터베이스 password

  jpa:
    hibernate:
      ddl-auto: validate # 검증만 하고 실제 DDL(CREATE, ALTER) 수행 X
    show-sql: false     # 콘솔에 SQL 출력 X(보안 및 성능)

  # MyBatis SQL 로그를 콘솔에 출력하기 위한 설정
  logging:
    level:
      com.kstec.idpportal.domain: INFO

  mybatis:
    configuration:
      default-statement-timeout: 10 # 운영은 좀 더 빠른 응답을 위해 10초로 제한